import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — StewardMe",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1 className="text-2xl font-semibold">Terms of Service</h1>
      <p className="mt-1 text-sm text-muted-foreground">
        Last updated: February 23, 2026
      </p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed">
        <section>
          <h2 className="text-lg font-medium">1. Acceptance</h2>
          <p className="mt-2">
            By accessing or using StewardMe, you agree to these terms. If you
            do not agree, do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium">2. Description of Service</h2>
          <p className="mt-2">
            StewardMe is an AI-powered personal advisor that combines journal
            reflections, goal tracking, and external intelligence to provide
            personalized guidance. The service requires an LLM API key that you
            provide.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium">3. Your Responsibilities</h2>
          <p className="mt-2">
            You are responsible for maintaining the security of your account and
            API keys. You agree not to use the service for any unlawful purpose
            or to abuse third-party APIs through the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium">4. Your Content</h2>
          <p className="mt-2">
            You retain ownership of all content you create (journal entries,
            goals, etc.). We do not claim any rights to your content. Content
            may be sent to your configured LLM provider to generate responses.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium">5. AI-Generated Content</h2>
          <p className="mt-2">
            Advice and recommendations are generated by AI and should not be
            treated as professional, financial, or medical advice. You are
            responsible for decisions made based on AI output.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium">6. Availability</h2>
          <p className="mt-2">
            We strive to keep the service available but do not guarantee uptime.
            The service may be modified or discontinued at any time.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium">7. Limitation of Liability</h2>
          <p className="mt-2">
            StewardMe is provided &quot;as is&quot; without warranties. We are
            not liable for any damages arising from your use of the service,
            including reliance on AI-generated content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium">8. Contact</h2>
          <p className="mt-2">
            Questions about these terms can be directed to{" "}
            <a href="mailto:support@stewardme.ai" className="text-primary underline">
              support@stewardme.ai
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
