"""Compatibility wrapper for the canonical user_state_store module."""

from user_state_store import (
    _DEFAULT_DB_PATH,
    _get_conn,
    add_user_rss_feed,
    clear_onboarding_responses,
    delete_user,
    delete_user_secret,
    get_all_user_rss_feeds,
    get_default_db_path,
    get_engagement_stats,
    get_feedback_count,
    get_onboarding_responses,
    get_or_create_user,
    get_usage_stats,
    get_user_name,
    get_user_rss_feeds,
    get_user_secret,
    get_user_secrets,
    get_user_usage_stats,
    init_db,
    log_engagement,
    log_event,
    remove_user_rss_feed,
    save_onboarding_turn,
    set_user_secret,
    update_user_name,
)

__all__ = [
    "_DEFAULT_DB_PATH",
    "_get_conn",
    "add_user_rss_feed",
    "clear_onboarding_responses",
    "delete_user",
    "delete_user_secret",
    "get_all_user_rss_feeds",
    "get_default_db_path",
    "get_engagement_stats",
    "get_feedback_count",
    "get_onboarding_responses",
    "get_or_create_user",
    "get_usage_stats",
    "get_user_name",
    "get_user_rss_feeds",
    "get_user_secret",
    "get_user_secrets",
    "get_user_usage_stats",
    "init_db",
    "log_engagement",
    "log_event",
    "remove_user_rss_feed",
    "save_onboarding_turn",
    "set_user_secret",
    "update_user_name",
]
